### ISSUE TITLE
YT button removal violates YT TOS

### ISSUE THREAD

**Issue by wchristian** [wonga00/astronaut#5]
The change was introduced with this commit:

https://github.com/wonga00/astronaut/commit/724d8a7da99706f83a0cf205a138dbd7dd52acc2

```css
+  pointer-events: none;
```

Relevant part of the TOS:

> 4.F. If you use the Embeddable Player on your website, you may not modify, build upon, or block any portion or functionality of the Embeddable Player, including but not limited to links back to the YouTube website.

https://www.youtube.com/static?template=terms&gl=US

**Comment by wonga00** [comment]
thx for picking this up -- made the change and deployed
