### ISSUE TITLE
Background video won't repeat

### ISSUE THREAD

**Issue by cakenggt** [wonga00/astronaut#6]
I'm not sure how long the background video is, but at a certain point it won't repeat anymore on chrome browsers. I don't know if this is after successful repeats, or if it has never repeated for me. No error is logged to the console when this happens.

**Comment by wonga00** [comment]
i believe it's because the static serving of the mp4 can't handle loop requests. fixed with javascript in 2317a0c455f95ffa7e431e6bd57ff378b839718b
